src/webserver/django/rethmeter/devices/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('sensors', views.SensorListView.as_view(), name='sensors'),
    path('api/measurement', views.api_sensor_data)
]

src/webserver/django/rethmeter/rethmeter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('devices/', include('devices.urls')),
    path('', RedirectView.as_view(url='devices/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/webserver/django/rethmeter/devices/models.py
from django.db import models
import uuid


class Device(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Device unique registration id.")
    name = models.CharField(max_length=32, help_text="Name of the device.")
    description = models.TextField(max_length=1000, help_text="Description of the device.")
    created = models.DateTimeField(auto_now_add=True, help_text="Registration date.")

    def __str__(self) -> str:
        return f"Device(name={self.name}, id={self.id})"


class Sensor(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Sensor unique id.")
    name = models.CharField(max_length=32, help_text="Sensor name.")
    parent = models.ForeignKey(Device, on_delete=models.CASCADE, help_text="Parent device of the sensor.")

    def __str__(self) -> str:
        return f"Sensor(name={self.name}, parent={self.parent})"


class Measurement(models.Model):
    date = models.DateTimeField(auto_now_add=True, help_text="Measurement creation date.")
    value = models.IntegerField(help_text="Measurement value.")
    unit = models.CharField(max_length=16, help_text="Measurement unit.")
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE, help_text="Measurement source.")

    class Meta:
        ordering = ['sensor__id', 'date']

    def __str__(self) -> str:
        return f"Measurement(date={self.date}, value={self.value}, unit={self.unit}, sensor={self.sensor.id})"

src/webserver/django/rethmeter/devices/views.py
import json
import logging
import os
from json.decoder import JSONDecodeError
from django.http.request import HttpRequest
from jsonschema.exceptions import ValidationError
from jsonschema import validate, Draft7Validator
from django.http.response import HttpResponse, HttpResponseNotAllowed, HttpResponseServerError, JsonResponse
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .models import Device, Sensor, Measurement


logger = logging.getLogger(__name__)


MEASUREMENT_SCHEMA_FILE = os.path.join(os.path.dirname(__file__), "schemas", "measurement.json")


class SensorListView(generic.ListView):
    model = Sensor
    template_name = 'sensors.html'


def index(request):
    context = {}

    devices = Device.objects.all()

    context['devices'] = [
        {
            'uuid': d.id,
            'name': d.name,
            'sensors': []
        } for d in devices or []
    ]

    for device in context['devices'] or []:
        sensors = Sensor.objects.filter(parent__exact=device['uuid'])

        device['sensors'] = [
            {
                'uuid': m.id,
                'num_measurements': Measurement.objects.filter(sensor__exact=m.id).count()
            } for m in sensors
        ]

    return render(request, 'index.html', context=context)


class JSONResponse(JsonResponse):
    def __init__(self, message: str, status: int, **kwargs) -> None:
        data = {"message": message, "code": status}
        super().__init__(data=data, status=status, **kwargs)


@csrf_exempt
def api_sensor_data(request: HttpRequest) -> JSONResponse:
    try:
        data = json.loads(request.body.decode())
    except JSONDecodeError as e:
        return JSONResponse(message="Decoding of JSON failed: %s" % e, status=HttpResponseBadRequest.status_code)
    except Exception as e:
        return JSONResponse(message="Unhandled error when decoding JSON: %s" % e, status=HttpResponseBadRequest.status_code)

    try:
        with open(MEASUREMENT_SCHEMA_FILE, "r") as fh:
            try:
                schema = json.load(fh)
            except JSONDecodeError:
                return JSONResponse(message="Decoding schema file failed. Check server logs.", status=HttpResponseServerError.status_code)
            try:
                validate(data, schema, cls=Draft7Validator)
            except ValidationError as e:
                logger.error("Measurement POST request rejected: Validation error: %s", e.message)
                return JSONResponse(message="Invalid format: %s" % e.message, status=HttpResponseBadRequest.status_code)
    except Exception as e:
        logger.exception("Unhandled error while validating request body:")
        return JSONResponse(message="Unexpected error while validating request body. Check server logs.", status=HttpResponseBadRequest.status_code)

    return JSONResponse(message="SUCCESS", status=HttpResponse.status_code)

src/webserver/django/rethmeter/devices/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    {% block title %}<title>Rethmeter</title>{% endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'sensors' %}">Sensors</a></li>
                    <li><a href="">Measurements</a></li>
                </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

src/webserver/django/rethmeter/devices/templates/index.html
{% extends 'base.html' %}

{% block content %}

<table>
    <caption>Devices</caption>

    <thead>
        <tr>
            <th>NAME</th>
            <th>ID</th>
        </tr>
    </thead>

    <tbody>
        {% for d in devices %}
        <tr>
            <td>{{d.name}}</td>
            <td>{{d.uuid}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

src/webserver/django/rethmeter/devices/templates/sensors.html
{% extends "base.html" %}

{% block content %}
  <h1>Sensors</h1>
  {% if sensor_list %}
  <ul>
    {% for sensor in sensor_list %}
      <li>
        <a href="{{ sensor.get_absolute_url }}">{{ sensor.name }}</a> ({{sensor.id}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No sensors found from database.</p>
  {% endif %}
{% endblock %}